[package]
name = "rparallel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5.2"
structopt = "^0.3.21"
regex = "1.5.5"
rand_pcg = "0.3.1"
rand = "0.8.5"